version: "3"

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5436:5432"
    networks:
      - my_network

  backend:
    image: ${BACKEND_VERSION}
    container_name: clewe-app
    hostname: clewe-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./
    volumes:
      - ./:/home/ubuntu/clewe
    environment:
      - MODE=wsgi
    ports:
      - "8005:8000"
    networks:
      - my_network

volumes:
  postgres-data:

networks:
  my_network:
    driver: bridge
