version: '3'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
    - "5435:5432"
    networks:
      - my_network

  backend:
    image: ${BACKEND_VERSION}
    container_name: clewe-app
    hostname: clewe-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./
    volumes:
      - ./:/home/ubuntu/clewe
    environment:
      - MODE=wsgi
    ports:
      - "8000:8000"
    networks:
      - my_network
  frontend:
    image: ${FRONTEND_VERSION}
    container_name: frontend
    restart: always
    build:
      context: ./
      dockerfile: frontend.dockerfile

    env_file:
      - .env
    healthcheck:
      test: curl -f http://localhost:3000/ping/
    ports:
      - '3000:3000'
    environment:
      NODE_OPTIONS: '--max-old-space-size=1024'
    networks:
      - my_network


volumes:
  postgres-data:

networks:
  my_network:
    driver: bridge