"""

Revision ID: 072ff2e1593c
Revises: 
Create Date: 2023-03-17 18:50:13.993494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072ff2e1593c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('skill_reward', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('exp_reward', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quest')),
    sa.UniqueConstraint('slug', name=op.f('uq_quest_slug'))
    )
    op.create_index(op.f('ix_quest_id'), 'quest', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('wallet_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('level_total_exp', sa.Integer(), nullable=True),
    sa.Column('exp_to_next_level', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_skill_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill'))
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_index(op.f('ix_skill_user_id'), 'skill', ['user_id'], unique=False)
    op.create_table('trophy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tx_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_trophy_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trophy')),
    sa.UniqueConstraint('tx_hash', name=op.f('uq_trophy_tx_hash'))
    )
    op.create_index(op.f('ix_trophy_id'), 'trophy', ['id'], unique=False)
    op.create_index(op.f('ix_trophy_user_id'), 'trophy', ['user_id'], unique=False)
    op.create_table('users_quests',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('quest', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest'], ['quest.id'], name=op.f('fk_users_quests_quest_quest')),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name=op.f('fk_users_quests_user_user')),
    sa.PrimaryKeyConstraint('user', 'quest', name=op.f('pk_users_quests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_quests')
    op.drop_index(op.f('ix_trophy_user_id'), table_name='trophy')
    op.drop_index(op.f('ix_trophy_id'), table_name='trophy')
    op.drop_table('trophy')
    op.drop_index(op.f('ix_skill_user_id'), table_name='skill')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_quest_id'), table_name='quest')
    op.drop_table('quest')
    # ### end Alembic commands ###
