"""

Revision ID: 379839a29979
Revises: bede9af21966
Create Date: 2023-06-06 19:30:43.673893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379839a29979'
down_revision = 'bede9af21966'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userskill', sa.Column('point', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userskill', 'point')
    # ### end Alembic commands ###
