"""

Revision ID: 7bbb3b7ef9a8
Revises: 036382dc5440
Create Date: 2023-06-29 19:21:08.505066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbb3b7ef9a8'
down_revision = '036382dc5440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('nfts', sa.JSON(), nullable=True))
    op.create_unique_constraint(op.f('uq_usertable_nickname'), 'usertable', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_usertable_nickname'), 'usertable', type_='unique')
    op.drop_column('usertable', 'nfts')
    # ### end Alembic commands ###
