"""

Revision ID: b58a82123750
Revises: 7d3c3c967f81
Create Date: 2023-04-22 16:25:36.316596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58a82123750'
down_revision = '7d3c3c967f81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('email', sa.VARCHAR(length=128), nullable=True))
    op.add_column('usertable', sa.Column('password', sa.Text(), nullable=True))
    op.create_index(op.f('ix_usertable_email'), 'usertable', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usertable_email'), table_name='usertable')
    op.drop_column('usertable', 'password')
    op.drop_column('usertable', 'email')
    # ### end Alembic commands ###
