"""

Revision ID: bede9af21966
Revises: 
Create Date: 2023-06-06 16:29:07.472412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bede9af21966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basequestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('MultipleOptions', 'SingleOption', 'OpenedText', name='questiontype'), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('experience_reward', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basequestion'))
    )
    op.create_index(op.f('ix_basequestion_id'), 'basequestion', ['id'], unique=False)
    op.create_table('baseskill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baseskill'))
    )
    op.create_index(op.f('ix_baseskill_id'), 'baseskill', ['id'], unique=False)
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_value', sa.Integer(), nullable=True),
    sa.Column('total_exp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level')),
    sa.UniqueConstraint('level_value', name=op.f('uq_level_level_value'))
    )
    op.create_index(op.f('ix_level_id'), 'level', ['id'], unique=False)
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quest'))
    )
    op.create_index(op.f('ix_quest_id'), 'quest', ['id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('MultipleOptions', 'SingleOption', 'OpenedText', name='questiontype'), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('experience_reward', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], name=op.f('fk_question_quest_id_quest'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_table('usertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('wallet_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('level_accumulated_exp', sa.Integer(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], name=op.f('fk_usertable_level_id_level'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usertable'))
    )
    op.create_index(op.f('ix_usertable_email'), 'usertable', ['email'], unique=True)
    op.create_index(op.f('ix_usertable_id'), 'usertable', ['id'], unique=False)
    op.create_index(op.f('ix_usertable_level_id'), 'usertable', ['level_id'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_skill_question_id_question'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill'))
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('userskill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usertable.id'], name=op.f('fk_userskill_user_id_usertable'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userskill'))
    )
    op.create_index(op.f('ix_userskill_id'), 'userskill', ['id'], unique=False)
    op.create_table('usersquests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], name=op.f('fk_usersquests_quest_id_quest'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['usertable.id'], name=op.f('fk_usersquests_user_id_usertable'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'quest_id', name=op.f('pk_usersquests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersquests')
    op.drop_index(op.f('ix_userskill_id'), table_name='userskill')
    op.drop_table('userskill')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_usertable_level_id'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_id'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_email'), table_name='usertable')
    op.drop_table('usertable')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_quest_id'), table_name='quest')
    op.drop_table('quest')
    op.drop_index(op.f('ix_level_id'), table_name='level')
    op.drop_table('level')
    op.drop_index(op.f('ix_baseskill_id'), table_name='baseskill')
    op.drop_table('baseskill')
    op.drop_index(op.f('ix_basequestion_id'), table_name='basequestion')
    op.drop_table('basequestion')
    # ### end Alembic commands ###
